"""EinkTerminal mixin: shell/PTY spawn, prompt building, TTY raw mode, scrollback."""
from __future__ import annotations

import fcntl
import getpass
import logging
import os
import pty
import pwd
import shlex
import shutil
import signal
import socket
import struct
import subprocess
import termios
import tty

import pyte

from terminal_renderer import SPLIT_TERMINAL_W, terminal_dimensions
from terminal_state import _REPO_ROOT

logger = logging.getLogger(__name__)


class ShellMixin:
    """PTY/shell lifecycle, custom prompt construction, TTY raw mode, scrollback."""

    @staticmethod
    def _write_signal_script(bindir: str, names, signum: int, description: str):
        """Write a `sh` script that signals this process (PID from
        /tmp/eink-terminal-active, written by run()) under each name in
        `names`. Shared by every typeable command in _install_command_scripts
        below — settings/clear-eink/notes/llmchat/terminal all follow this
        exact shape, differing only in which signal they send."""
        script = (
            '#!/bin/sh\n'
            f'# {description} Auto-generated by eink_terminal_app.py — edits\n'
            '# will be overwritten on launch.\n'
            'pidfile=/tmp/eink-terminal-active\n'
            f'if [ -r "$pidfile" ] && kill -{signum} "$(cat "$pidfile")" 2>/dev/null; then\n'
            '    exit 0\n'
            'fi\n'
            'echo "e-ink terminal not running (no $pidfile)" >&2\n'
            'exit 1\n'
        )
        for name in names:
            path = os.path.join(bindir, name)
            with open(path, 'w') as f:
                f.write(script)
            os.chmod(path, 0o755)

    def _install_command_scripts(self):
        """Drop helper commands into data/bin and prepend it to PATH, so the
        spawned shell can open in-app overlays / switch modes by name.

        Each script signals this process — e.g. `settings` sends SIGUSR1 to
        open the config editor. Generated at launch so they always match the
        running app."""
        bindir = os.path.join(_REPO_ROOT, 'data', 'bin')
        try:
            os.makedirs(bindir, exist_ok=True)
            self._write_signal_script(bindir, ('settings', 'eink'), signal.SIGUSR1,
                                       'Opens the e-ink on-display Settings editor.')
            self._write_signal_script(bindir, ('clear-eink',), signal.SIGUSR2,
                                       'Clears the e-ink terminal (screen + ghosting).')
            self._write_signal_script(bindir, ('notes',), signal.SIGRTMIN + 1,
                                       'Switches the e-ink terminal to Notes mode.')
            self._write_signal_script(bindir, ('llmchat',), signal.SIGRTMIN + 2,
                                       'Switches the e-ink terminal to local LLM chat mode.')
            self._write_signal_script(bindir, ('terminal',), signal.SIGRTMIN + 3,
                                       'Switches the e-ink terminal back to a plain shell tab.')
        except OSError as e:
            logger.warning('could not install command scripts: %s', e)
            return
        # Prepend to the parent's PATH so the forked shell — and tmux, which
        # inherits the client environment — both find the commands.
        cur = os.environ.get('PATH', '')
        if bindir not in cur.split(os.pathsep):
            os.environ['PATH'] = bindir + os.pathsep + cur

    def _on_settings_signal(self, signum, frame):
        """SIGUSR1 handler — set a flag for the main loop. Kept minimal so it's
        safe to run from a signal context (no rendering or I/O here)."""
        self._open_settings_requested = True

    def _on_clear_signal(self, signum, frame):
        """SIGUSR2 handler (`clear-eink`) — flag a screen clear for the loop."""
        self._clear_requested = True

    def _on_notes_signal(self, signum, frame):
        """SIGRTMIN+1 handler (`notes` command) — flag a mode switch for the loop."""
        self._notes_requested = True

    def _on_llm_chat_signal(self, signum, frame):
        """SIGRTMIN+2 handler (`llmchat` command) — flag a mode switch for the loop."""
        self._llm_chat_requested = True

    def _on_terminal_signal(self, signum, frame):
        """SIGRTMIN+3 handler (`terminal` command) — flag a mode switch for the loop."""
        self._terminal_requested = True

    def _on_shutdown_signal(self, signum, frame):
        """SIGINT/SIGTERM — request a graceful shutdown instead of crashing.

        In raw-keyboard mode Ctrl+C is forwarded to the shell as a byte and this
        never fires; it matters when stdin is left cooked (evdev keyboard, or an
        SSH session driving the app) so a stray Ctrl+C cleans up the panel
        instead of killing the process mid-refresh."""
        self._running = False

    # ─── Screen ──────────────────────────────────────────────────────────────

    def _init_screen(self):
        tw = SPLIT_TERMINAL_W if self._split_view else 800
        cols, rows, cw, ch = terminal_dimensions(self._font_size, self._font_path, tw)
        if hasattr(self, '_driver'):
            self._driver.set_cell_size(cw, ch)
        if self._use_tmux:
            self._screen = pyte.Screen(cols, rows)
        else:
            history = self._config.get('terminal_scrollback', 500)
            self._screen = pyte.HistoryScreen(cols, rows, history=history)
        self._stream = pyte.ByteStream(self._screen)
        self._scroll_pages = 0

    # ─── PTY ─────────────────────────────────────────────────────────────────

    def _spawn_shell(self, tmux_session: str = None):
        session = tmux_session if tmux_session is not None else self._tmux_session
        # Resolve everything that needs the filesystem in the parent, before the
        # fork, so the forked child only execs.
        start_dir = self._resolve_start_dir()
        promptcmd = self._build_prompt_command()   # None unless custom prompt is on
        pid, master_fd = pty.fork()
        if pid == 0:
            os.environ['TERM'] = 'xterm-256color'
            if self._use_tmux:
                os.execvp('tmux', self._tmux_launch_argv(session, start_dir, promptcmd))
            else:
                if start_dir:
                    try:
                        os.chdir(start_dir)
                    except OSError:
                        pass
                if promptcmd:
                    # An interactive shell wired up with our custom prompt. The
                    # leading 'exec' replaces this sh, so no extra layer remains.
                    os.execvp('/bin/sh', ['/bin/sh', '-c', promptcmd])
                shell = os.environ.get('SHELL') or pwd.getpwuid(os.getuid()).pw_shell or '/bin/bash'
                # Start as a login shell (argv[0] prefixed with '-') so it behaves
                # like a normal console terminal: sources /etc/profile + ~/.profile,
                # sets PATH, shows the user's real prompt, prints MOTD/last-login.
                argv0 = '-' + os.path.basename(shell)
                os.execvp(shell, [argv0])
            os._exit(1)
        self._child_pid = pid
        self._pty_master = master_fd
        self._sync_pty_winsize()

    def _tmux_launch_argv(self, session: str, start_dir: str, promptcmd: str) -> list:
        """argv for `tmux new-session -A` (attach-or-create).

        When a custom prompt is active we run our custom-prompt shell as the pane
        command AND set it as the session's default-command, so every future
        window/pane (split, new-window, …) gets the same prompt — not just the
        first one. Attaching an existing session keeps its panes/cwd ('last')."""
        argv = ['tmux', 'new-session', '-A', '-s', session]
        if start_dir:
            argv += ['-c', start_dir]
        if promptcmd:
            # initial pane command, then default-command for subsequent panes.
            argv += [promptcmd, ';', 'set-option', 'default-command', promptcmd]
        return argv

    # ─── Start directory ──────────────────────────────────────────────────────

    @property
    def _last_cwd_file(self) -> str:
        return os.path.join(_REPO_ROOT, 'data', 'last_cwd.txt')

    def _resolve_start_dir(self) -> str | None:
        """Turn the terminal_start_dir preference into a concrete directory.
        Falls back to $HOME for anything missing/invalid. None = don't force."""
        pref = str(self._start_dir_pref or 'home').strip()
        home = os.path.expanduser('~')
        if pref == 'home':
            return home
        if pref == 'root':
            return '/'
        if pref == 'last':
            return self._read_last_cwd() or home
        path = os.path.expanduser(pref)
        return path if os.path.isdir(path) else home

    def _read_last_cwd(self) -> str | None:
        try:
            d = open(self._last_cwd_file).read().strip()
            return d if d and os.path.isdir(d) else None
        except OSError:
            return None

    def _save_last_cwd(self):
        """Persist the active shell's current directory so 'last' can resume it
        after a restart/reboot. tmux: query the active pane; else read /proc."""
        d = None
        try:
            if self._use_tmux and shutil.which('tmux'):
                r = subprocess.run(
                    ['tmux', 'display-message', '-p', '-t', self._tmux_session,
                     '#{pane_current_path}'],
                    capture_output=True, text=True, timeout=1)
                d = r.stdout.strip()
            elif self._child_pid:
                d = os.readlink('/proc/%d/cwd' % self._child_pid)
        except Exception:
            d = None
        if d and os.path.isdir(d):
            try:
                os.makedirs(os.path.dirname(self._last_cwd_file), exist_ok=True)
                with open(self._last_cwd_file, 'w') as f:
                    f.write(d + '\n')
            except OSError:
                pass

    # ─── Custom shell prompt (bash / zsh / fish) ──────────────────────────────

    # Per-shell prompt escapes for the user@host:cwd segments. bash and zsh
    # share the git command substitution (POSIX $()); fish is built separately.
    _PROMPT_ESC = {
        'bash': {'user': r'\u', 'host': r'\h', 'cwd': r'\w'},
        'zsh':  {'user': '%n',  'host': '%m',  'cwd': '%~'},
    }

    def _detect_shell(self) -> str:
        """Basename of the user's login shell: 'bash', 'zsh', 'fish', …"""
        shell = os.environ.get('SHELL') or ''
        if not shell:
            try:
                shell = pwd.getpwuid(os.getuid()).pw_shell
            except Exception:
                shell = ''
        return os.path.basename(shell or '/bin/bash')

    def _build_prompt_string(self, kind: str) -> str:
        """PS1/PROMPT string for a POSIX-prompt shell (bash or zsh) from the
        enabled parts. Quoted so the shell expands the escapes + git command
        substitution fresh on each prompt."""
        esc = self._PROMPT_ESC[kind]
        ident = ''
        if self._prompt_show_user:
            ident += esc['user']
        if self._prompt_show_host:
            ident += ('@' if ident else '') + esc['host']
        segs = []
        if ident:
            segs.append(ident)
        if self._prompt_show_cwd:
            segs.append(esc['cwd'])
        prompt = ':'.join(segs)
        if self._prompt_show_git:
            # Show " (branch)" only inside a git work tree; silent otherwise.
            prompt += r'$(__b=$(git branch --show-current 2>/dev/null); [ -n "$__b" ] && printf " (%s)" "$__b")'
        sym = self._prompt_symbol or '$'
        return (prompt + ' ' if prompt else '') + sym + ' '

    def _build_ps1(self) -> str:
        """Bash PS1 (kept as a named helper; preview/tests use it)."""
        return self._build_prompt_string('bash')

    def _build_fish_prompt(self) -> str:
        """A `function fish_prompt … end` definition (fish has no PS1)."""
        ident = []
        if self._prompt_show_user:
            ident.append('$USER')
        if self._prompt_show_host:
            ident.append('(prompt_hostname)')
        id_str = "'@'".join(ident)
        parts = []
        if id_str:
            parts.append(id_str)
        if self._prompt_show_cwd:
            parts.append('(prompt_pwd)')
        head = "':'".join(parts)
        sym = (self._prompt_symbol or '$').replace("'", r"\'")
        lines = ['function fish_prompt']
        if head:
            lines.append('    echo -n ' + head)
        if self._prompt_show_git:
            lines.append('    set -l __b (git branch --show-current 2>/dev/null)')
            lines.append('    test -n "$__b"; and echo -n " ($__b)"')
        lines.append("    echo -n ' %s '" % sym)
        lines.append('end')
        return '\n'.join(lines)

    def _build_prompt_command(self) -> str | None:
        """Shell command that launches an interactive shell wired up with our
        custom prompt — used both as the tmux pane command / default-command and
        (via `sh -c`) for the non-tmux exec. None when the custom prompt is off.

        Honors the user's actual $SHELL: zsh and fish get their native prompt
        mechanism; everything else (and unknown shells) uses bash, since the
        POSIX prompt escapes are bash syntax."""
        if not self._prompt_custom:
            return None
        shell = self._detect_shell()
        if shell == 'zsh' and shutil.which('zsh'):
            zdotdir = self._write_zsh_dotdir()
            if zdotdir:
                return 'exec env ZDOTDIR=%s zsh -i' % shlex.quote(zdotdir)
        elif shell == 'fish' and shutil.which('fish'):
            return 'exec fish -i -C %s' % shlex.quote(self._build_fish_prompt())
        rc = self._write_bash_rcfile()
        if rc:
            return 'exec bash --rcfile %s -i' % shlex.quote(rc)
        return None

    def _prompt_rcfile_path(self) -> str:
        return os.path.join(_REPO_ROOT, 'data', 'eink_bashrc')

    def _write_bash_rcfile(self) -> str | None:
        """bash rcfile that replays login-shell startup (so PATH, aliases, etc.
        match a normal terminal), then pins our PS1 last. Returns its path, or
        None on write failure. Used as `bash --rcfile <path> -i`."""
        ps1 = self._build_prompt_string('bash').replace("'", "'\\''")
        content = (
            "# Auto-generated by the e-ink terminal — regenerated on launch from\n"
            "# config.yaml. Replays login-shell startup, then pins the custom PS1.\n"
            "[ -r /etc/profile ] && . /etc/profile\n"
            'for __f in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do\n'
            '    [ -r "$__f" ] && { . "$__f"; break; }\n'
            "done\n"
            "PS1='" + ps1 + "'\n"
        )
        path = self._prompt_rcfile_path()
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w') as f:
                f.write(content)
        except OSError:
            return None
        return path

    def _write_zsh_dotdir(self) -> str | None:
        """Create a ZDOTDIR whose .zshrc sources the user's real one then pins
        PROMPT. .zshenv is chained back too so login env is preserved despite the
        overridden ZDOTDIR. Returns the dir, or None on failure."""
        prompt = self._build_prompt_string('zsh').replace("'", "'\\''")
        d = os.path.join(_REPO_ROOT, 'data', 'eink_zdotdir')
        try:
            os.makedirs(d, exist_ok=True)
            with open(os.path.join(d, '.zshenv'), 'w') as f:
                f.write('[ -r "$HOME/.zshenv" ] && source "$HOME/.zshenv"\n')
            with open(os.path.join(d, '.zshrc'), 'w') as f:
                f.write(
                    "# Auto-generated by the e-ink terminal.\n"
                    '[ -r "$HOME/.zshrc" ] && source "$HOME/.zshrc"\n'
                    "setopt prompt_subst\n"
                    "PROMPT='" + prompt + "'\n"
                )
        except OSError:
            return None
        return d

    # ─── Prompt preview (shown live in the settings editor) ────────────────────

    def _prompt_preview(self) -> str:
        """A representative expansion of the configured prompt parts, using real
        user/host but placeholder dir/branch — so the editor can show the effect
        before saving. Reads staged (pending) values via _settings_value."""
        if not self._settings_value('terminal_prompt_custom',
                                    self._config.get('terminal_prompt_custom', False)):
            return '(custom prompt off)'

        def on(key):
            return bool(self._settings_value(key, self._config.get(key, True)))

        try:
            user = getpass.getuser()
        except Exception:
            user = 'user'
        host = socket.gethostname().split('.')[0]
        ident = ''
        if on('terminal_prompt_show_user'):
            ident += user
        if on('terminal_prompt_show_host'):
            ident += ('@' if ident else '') + host
        segs = [ident] if ident else []
        if on('terminal_prompt_show_cwd'):
            segs.append('~/project')
        s = ':'.join(segs)
        if on('terminal_prompt_show_git'):
            s += ' (main)'
        sym = self._settings_value('terminal_prompt_symbol',
                                   self._config.get('terminal_prompt_symbol', '$')) or '$'
        return (s + ' ' if s else '') + sym

    def _sync_pty_winsize(self):
        tw = SPLIT_TERMINAL_W if self._split_view else 800
        cols, rows, _, _ = terminal_dimensions(self._font_size, self._font_path, tw)
        winsize = struct.pack('HHHH', rows, cols, 0, 0)
        try:
            fcntl.ioctl(self._pty_master, termios.TIOCSWINSZ, winsize)
        except Exception as e:
            logger.warning('Could not set PTY window size: %s', e)

    # ─── TTY raw mode ─────────────────────────────────────────────────────────

    def _enter_raw(self):
        if self._evdev_kb:
            return  # evdev handles input; stdin raw mode not needed
        try:
            self._old_tty = termios.tcgetattr(self._stdin_fd)
            tty.setraw(self._stdin_fd)
        except termios.error:
            pass  # not a real TTY (e.g. systemd without StandardInput=tty)

    def _exit_raw(self):
        if self._old_tty is not None:
            try:
                termios.tcsetattr(self._stdin_fd, termios.TCSADRAIN, self._old_tty)
            except Exception:
                pass

    # ─── Scrollback ───────────────────────────────────────────────────────────

    def _scroll_up(self):
        if self._use_tmux or not hasattr(self._screen, 'prev_page'):
            return
        self._screen.prev_page()
        self._scroll_pages += 1
        self._render(force_full=True)

    def _scroll_down(self):
        if self._use_tmux or not hasattr(self._screen, 'next_page'):
            return
        if self._scroll_pages > 0:
            self._screen.next_page()
            self._scroll_pages -= 1
            self._render(force_full=True)

    def _snap_to_live(self):
        """Snap back to live view if currently scrolled up."""
        while self._scroll_pages > 0 and hasattr(self._screen, 'next_page'):
            self._screen.next_page()
            self._scroll_pages -= 1
